# Generated by Django 5.1.6 on 2025-03-25 14:39

import attendance.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(blank=True, max_length=50, null=True)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='AdminProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('updation_date', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Guard',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=128)),
                ('gender', models.CharField(max_length=6)),
                ('profile_pic', models.FileField(default='guard_images/user-default-min.png', upload_to='guard_images', validators=[attendance.models.validate_file_extension])),
                ('birth_date', models.DateField()),
                ('hire_date', models.DateField()),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.department')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.location')),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=6)),
                ('in_time', models.IntegerField()),
                ('notes', models.CharField(blank=True, max_length=120)),
                ('image', models.CharField(blank=True, max_length=50)),
                ('lack_of', models.CharField(blank=True, max_length=11)),
                ('in_status', models.CharField(max_length=15)),
                ('out_time', models.IntegerField(blank=True, null=True)),
                ('out_status', models.CharField(blank=True, max_length=15)),
                ('status', models.IntegerField(choices=[(0, 'Pending'), (1, 'Approved'), (2, 'Rejected')])),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.department')),
                ('guard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.guard')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.location')),
            ],
        ),
    ]
