# Generated by Django 5.1.6 on 2025-03-06 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='username',
            new_name='name',
        ),
        migrations.AddField(
            model_name='department',
            name='code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
